FROM node:18-alpine3.15

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install

COPY . .

RUN npm run build

# stage two
FROM node:18-alpine3.15

WORKDIR /app

COPY package*.json ./

RUN npm install --only=production

COPY --from=0 /app/dist ./src

# EXPOSE 8000

CMD ["node", "src/server.js"]