name: Deploy to Production

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Create SSH key
              run: |
                  mkdir -p ~/.ssh/
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                  sudo chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
              env:
                  SSH_HOST: ${{secrets.SSH_HOST}}
                  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
            # - name: Connect to SSH
            #   run: |
            #       ${GITHUB_WORKSPACE}/scripts/ci/deploy.sh
            - name: Copy Files to Server
              run: |
                  # apt-get install rsync
                  rsync ${GITHUB_WORKSPACE}/LICENSE "$SSH_USER@$SSH_HOST:$SSH_DIR" -v -R
              env:
                  SSH_HOST: ${{secrets.SSH_HOST}}
                  SSH_DIR: ${{secrets.SSH_DIR}}
                  SSH_USER: ${{secrets.SSH_USER}}
