name: tests
run-name: Run Tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    tests:
        name: 'Node.js v${{ matrix.node }}'
        runs-on: ubuntu-latest
        # services:
        #     postgres:
        #         image: postgres
        #         env:
        #             POSTGRES_PASSWORD: postgres
        #         # Set health checks to wait until postgres has started
        #         options: >-
        #             --health-cmd pg_isready
        #             --health-interval 10s
        #             --health-timeout 5s
        #             --health-retries 5
        strategy:
            matrix:
                node:
                    - 18
        env:
            DB_ROOT_PASSWORD: password
            APP_PORT: 9999
            DB_HOST: localhost
            DB_PORT: 5432
            DB_NAME: app_db
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - name: Run Postgres container
              run: docker run --name db -e POSTGRES_PASSWORD=password -p 5432:5432 -d postgres -v ./scripts/db:/docker-entrypoint-initdb.d/
            - run: docker logs db
            - name: Apply DB migrations
              run: npm run migrate up
